# Generated by Django 5.1.3 on 2025-04-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_blog_content_alter_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
