# Generated by Django 5.1.3 on 2025-05-03 21:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_blog_featured_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("blog", "reviewer")},
        ),
    ]
