# Generated by Django 4.2.4 on 2025-05-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0005_alter_review_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="blogapp.tag"
            ),
        ),
    ]
